import { Kit } from '../types/kit';

/**
 * Downloads arbitrary text/blob data as a file in the browser.
 */
export function downloadFile(filename: string, content: string, mimeType: string = 'text/plain;charset=utf-8') {
  if (typeof window === 'undefined') return;
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Generates an RFC 5545 compliant iCalendar (.ics) string from the Kit's study schedule.
 */
export function generateIcsCalendar(kit: Kit, startDateTime: Date = new Date()): string {
  const pad = (n: number) => (n < 10 ? `0${n}` : `${n}`);
  const formatIcsDate = (d: Date) =>
    `${d.getUTCFullYear()}${pad(d.getUTCMonth() + 1)}${pad(d.getUTCDate())}T${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}${pad(d.getUTCSeconds())}Z`;

  const nowStr = formatIcsDate(new Date());
  const company = kit.source.company || 'Company';
  const role = kit.role.title || 'Interview Prep';

  let ics = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Trao AI//Interview Prep Kit Scheduler//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:${company} Interview Study Plan`,
    'X-WR-TIMEZONE:UTC'
  ];

  kit.schedule.days.forEach((day, index) => {
    // Start each day at 9:00 AM UTC of consecutive days
    const eventStart = new Date(startDateTime);
    eventStart.setUTCDate(eventStart.getUTCDate() + index + 1);
    eventStart.setUTCHours(9, 0, 0, 0);

    const minutes = day.minutes || 60;
    const eventEnd = new Date(eventStart.getTime() + minutes * 60 * 1000);

    const uid = `trao-kit-${kit.source.company.toLowerCase().replace(/[^a-z0-9]/g, '-')}-day-${day.day}-${index}@trao.ai`;
    const summary = `Day ${day.day}: ${day.focus} - ${company} (${role})`;
    
    // Find questions for this day
    const dayQuestions = kit.questions
      .filter((q) => day.question_ids.includes(q.id))
      .map((q, qIdx) => `${qIdx + 1}. [${q.category.toUpperCase()}] ${q.prompt}`)
      .join('\\n');

    const description = `🎯 Focus Area: ${day.focus}\\n⏱ Duration: ${minutes} Minutes\\n\\n📋 Practice Questions:\\n${dayQuestions || 'Review core flashcards and architecture notes.'}\\n\\nGenerated by Trao AI Interview Kit.`;

    ics.push(
      'BEGIN:VEVENT',
      `UID:${uid}`,
      `DTSTAMP:${nowStr}`,
      `DTSTART:${formatIcsDate(eventStart)}`,
      `DTEND:${formatIcsDate(eventEnd)}`,
      `SUMMARY:${summary.replace(/,/g, '\\,')}`,
      `DESCRIPTION:${description}`,
      'STATUS:CONFIRMED',
      'TRANSP:OPAQUE',
      'END:VEVENT'
    );
  });

  ics.push('END:VCALENDAR');
  return ics.join('\r\n');
}

/**
 * Generates Anki / Quizlet compatible TSV/CSV format from the Kit flashcards and questions.
 */
export function generateAnkiCsv(kit: Kit): string {
  // UTF-8 BOM for seamless Excel/Anki import
  let csv = '\uFEFF';
  csv += 'Front\tBack\tCategory\tTags\n';

  // 1. Export flashcards
  kit.flashcards.forEach((card) => {
    const cleanFront = card.front.replace(/\t/g, ' ').replace(/\n/g, '<br/>');
    const cleanBack = card.back.replace(/\t/g, ' ').replace(/\n/g, '<br/>');
    const tags = `Trao,${kit.source.company.replace(/\s+/g, '_')},Flashcard`;
    csv += `"${cleanFront}"\t"${cleanBack}"\t"Core Concept"\t"${tags}"\n`;
  });

  // 2. Export questions as Q&A flashcards
  kit.questions.forEach((q) => {
    const cleanFront = `[${q.category.toUpperCase()}] ${q.prompt}`.replace(/\t/g, ' ').replace(/\n/g, '<br/>');
    const cleanBack = q.answer_outline.replace(/\t/g, ' ').replace(/\n/g, '<br/>');
    const tags = `Trao,${kit.source.company.replace(/\s+/g, '_')},${q.category},Diff_${q.difficulty}`;
    csv += `"${cleanFront}"\t"${cleanBack}"\t"${q.category}"\t"${tags}"\n`;
  });

  return csv;
}

/**
 * Triggers clean PDF generation using browser printing engine with printable document layout.
 */
export function triggerPrintPdf(kit: Kit) {
  if (typeof window === 'undefined') return;
  window.print();
}
